name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/product-services/package-lock.json
        
      - name: Install Dependencies
        working-directory: services/product-services
        run: npm ci

      - name: Start Services
        run: docker compose up -d
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          PORT: ${{ secrets.PORT }}

      - name: Run Tests
        working-directory: services/product-services
        run: npm test
        
      - name: Stop Services
        if: always()
        run: docker compose down
        
  kubernetes-deployment:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t e-commerce-product-service:${{ github.sha }} ./services/product-services
          docker tag e-commerce-product-service:${{ github.sha }} e-commerce-product-service:latest

      - name: Set up minikube
        uses: medyagh/setup-minikube@latest

      - name: Load Docker Product image into minikube
        run: minikube image load e-commerce-product-service:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/postgres.yaml
          kubectl apply -f k8s/product-service.yaml

      - name: Wait for deployment
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/postgres -n ecommerce
          kubectl wait --for=condition=available --timeout=300s deployment/product-service -n ecommerce

      - name: Test deployment
        run: |
          echo "Testing deployment.."

          kubectl port-forward svc/product-service 3001:80 -n ecommerce 

          curl -f http://localhost:3001/health || exit 1

      - name: Show deployment status
        run: |
          echo "Deployment status: "
          kubectl get pods -n ecommerce
          kubectl get services -n ecommerce

